// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHQldAr_Q9e5BhvwndZ8qzUSBZpMX-US0',
    appId: '1:353261142637:web:c4ee656a93a3e3c5467564',
    messagingSenderId: '353261142637',
    projectId: 'campusone-saas',
    authDomain: 'campusone-saas.firebaseapp.com',
    storageBucket: 'campusone-saas.firebasestorage.app',
    measurementId: 'G-B41PGW5GZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1z3DYqf99-_5q4bEGlTAQbj8BoUYFOxQ',
    appId: '1:353261142637:android:150e8423dd411ff8467564',
    messagingSenderId: '353261142637',
    projectId: 'campusone-saas',
    storageBucket: 'campusone-saas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl7rLdSP_tLWT0NnqWRXeXInRWifcQS_0',
    appId: '1:353261142637:ios:9ba68454ce2c6bf5467564',
    messagingSenderId: '353261142637',
    projectId: 'campusone-saas',
    storageBucket: 'campusone-saas.firebasestorage.app',
    iosBundleId: 'com.example.campusone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl7rLdSP_tLWT0NnqWRXeXInRWifcQS_0',
    appId: '1:353261142637:ios:9ba68454ce2c6bf5467564',
    messagingSenderId: '353261142637',
    projectId: 'campusone-saas',
    storageBucket: 'campusone-saas.firebasestorage.app',
    iosBundleId: 'com.example.campusone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHQldAr_Q9e5BhvwndZ8qzUSBZpMX-US0',
    appId: '1:353261142637:web:d3b2f7524ad3fffc467564',
    messagingSenderId: '353261142637',
    projectId: 'campusone-saas',
    authDomain: 'campusone-saas.firebaseapp.com',
    storageBucket: 'campusone-saas.firebasestorage.app',
    measurementId: 'G-3ZRPHR2S5N',
  );
}
