import 'dart:io';

import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfService {
  static Future<void> generateReport({
    required int totalStudents,
    required int totalLecturers,
    required int totalCourses,
    required int totalDepartments,
    required int totalNotices,
  }) async {
    final pdf = pw.Document();

    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),

        build: (context) {
          return [

            pw.Center(
              child: pw.Text(
                "CampusOne",
                style: pw.TextStyle(
                  fontSize: 28,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),

            pw.SizedBox(height: 8),

            pw.Center(
              child: pw.Text(
                "Reports & Analytics",
                style: const pw.TextStyle(
                  fontSize: 18,
                ),
              ),
            ),

            pw.SizedBox(height: 25),

            pw.Divider(),

            pw.SizedBox(height: 15),

            pw.Text(
              "Generated On",
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
                fontSize: 14,
              ),
            ),

            pw.Text(
              "${now.day}/${now.month}/${now.year}   ${now.hour}:${now.minute.toString().padLeft(2, '0')}",
            ),

            pw.SizedBox(height: 25),

            pw.Table(
              border: pw.TableBorder.all(
                color: PdfColors.grey600,
              ),

              columnWidths: {
                0: const pw.FlexColumnWidth(3),
                1: const pw.FlexColumnWidth(1),
              },

              children: [

                _row("Total Students", totalStudents),

                _row("Total Lecturers", totalLecturers),

                _row("Total Courses", totalCourses),

                _row("Total Departments", totalDepartments),

                _row("Total Notices", totalNotices),

              ],
            ),

            pw.SizedBox(height: 40),

            pw.Divider(),

            pw.SizedBox(height: 10),

            pw.Center(
              child: pw.Text(
                "Generated by CampusOne Admin Panel",
                style: pw.TextStyle(
                  color: PdfColors.grey700,
                  fontSize: 12,
                ),
              ),
            ),

          ];
        },
      ),
    );

    final directory =
        await getApplicationDocumentsDirectory();

    final file = File(
      "${directory.path}/CampusOne_Report.pdf",
    );

    await file.writeAsBytes(
      await pdf.save(),
    );

    await OpenFilex.open(
      file.path,
    );
  }

  static pw.TableRow _row(
    String title,
    int value,
  ) {
    return pw.TableRow(
      children: [

        pw.Padding(
          padding: const pw.EdgeInsets.all(12),
          child: pw.Text(
            title,
          ),
        ),

        pw.Padding(
          padding: const pw.EdgeInsets.all(12),
          child: pw.Text(
            value.toString(),
          ),
        ),

      ],
    );
  }
}