import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PrintService {
  static Future<void> printReport({
    required int totalStudents,
    required int totalLecturers,
    required int totalCourses,
    required int totalDepartments,
    required int totalNotices,
  }) async {
    final pdf = pw.Document();

    final now = DateTime.now();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) {
          return [

            pw.Center(
              child: pw.Text(
                "CampusOne",
                style: pw.TextStyle(
                  fontSize: 28,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),

            pw.SizedBox(height: 8),

            pw.Center(
              child: pw.Text(
                "Reports & Analytics",
                style: const pw.TextStyle(
                  fontSize: 18,
                ),
              ),
            ),

            pw.SizedBox(height: 25),

            pw.Divider(),

            pw.SizedBox(height: 20),

            pw.Text(
              "Generated On",
              style: pw.TextStyle(
                fontWeight: pw.FontWeight.bold,
              ),
            ),

            pw.Text(
              "${now.day}/${now.month}/${now.year}",
            ),

            pw.SizedBox(height: 20),

            pw.Bullet(
              text: "Total Students : $totalStudents",
            ),

            pw.Bullet(
              text: "Total Lecturers : $totalLecturers",
            ),

            pw.Bullet(
              text: "Total Courses : $totalCourses",
            ),

            pw.Bullet(
              text: "Total Departments : $totalDepartments",
            ),

            pw.Bullet(
              text: "Total Notices : $totalNotices",
            ),

            pw.SizedBox(height: 35),

            pw.Divider(),

            pw.Center(
              child: pw.Text(
                "Generated by CampusOne",
              ),
            ),

          ];
        },
      ),
    );

    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async {
        return pdf.save();
      },
    );
  }
}